	
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pvaatoz/tusharportfolio.pvaatoz.com/
    # - export DEPLOYPATH=/home/pvaatoz/public_html/
    - /bin/cp * $DEPLOYPATH
    # - /bin/cp style.css $DEPLOYPATH